[package]
name = "soprano"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
glob = "0.3.1"
sqlx = { version = "0.8.2", features = ["mysql", "runtime-tokio"] }
tokio = { version = "1.40.0", features = ["full"] }
